# -*- coding: utf-8 -*-
"""Numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nFceKrFO1SCQQIXKDjuGYkJZD6bLGcBS
"""

import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)

print(type(arr))

import numpy as np
#Different Array with different dimensions
arr1=np.array(42) # 0 Dimensional Array
print(arr1)

arr2=np.array([1,2,3,4,5]) # 1 Dimensional Array
print(arr2)

arr3=np.array([[1,2,3],[4,5,6]]) # 2 Dimensional Array
print(arr3)

print(" ")

arr4=np.array(([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])) #3 Dimensional Array
print(arr4)


arr5=np.array([[[1,2,3],[1,2,3]],[[4,5,6],[4,5,6]]])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

import numpy as np
#Accessing the index of the Array

arr1=np.array([1,2,3,4,5])

print(arr1[0])
print(arr1[1]+arr1[4])

#Accessing the 2D Array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]]) #2 would be shown as the result

print(arr2.shape) #it shows the Columns and the Rows
print(arr2)
print(arr2[0,1])
print(arr2[1,4])


arr3=np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]],[[10,11,12]]])
print(arr3.ndim)
print(arr3.shape)

import numpy as np
#Array Slicing
arr=np.array(['a','b','c','d','e','f','g'])
print(arr[1:5])